services:
  app:
    build: .
    volumes:
      - ./logs:/code/logs
      - ./config.json:/code/config.json
    healthcheck:
      test: ["CMD", "pgrep", "node"]
      start_period: 10s
      timeout: 10s
    restart: on-failure
